name: 1.0.$(date:yyyyMMdd)$(rev:.rrr)
trigger:
  branches:
    include:
      - master
variables:
  imageNameFront: lab-survey-front:$(Build.BuildNumber)
  imageNameApi: lab-survey-api:$(Build.BuildNumber)
jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Docker@1
        displayName: 'Build front image'
        inputs:
          dockerFile: ./lab-survey-front/Dockerfile
          imageName: $(imageNameFront)
          workingDirectory: ./lab-survey-front
      - task: Docker@1
        displayName: 'Build api image'
        inputs:
          dockerFile: ./lab-survey-api/lab-survey-api/Dockerfile
          imageName: $(imageNameApi)
          workingDirectory: ./lab-survey-api/lab-s  urvey-api/
