variables:
  appVersion: 1.0.$(date:yyyyMMdd).$(rev:.rr)
  imageNameFront: lab-survey-front
  imageNameApi: lab-survey-api
name: 1.0.$(date:yyyyMMdd).$(rev:.rr)
jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Docker@1
        displayName: 'Build front image'
        inputs:
          dockerFile: ./lab-survey-front/Dockerfile
          imageName: $(imageNameFront):$(appVersion)
          workingDirectory: ./lab-survey-front
      - task: Docker@1
        displayName: 'Build api image'
        inputs:
          dockerFile: ./lab-survey-api/lab-survey-api/Dockerfile
          imageName: $(imageNameApi):$(appVersion)
          workingDirectory: ./lab-survey-api/lab-survey-api/
