variables:
  imageNameFront: 'lab-survey-front:$(Build.BuildId)'
  imageNameApi: 'lab-survey-api:$(Build.BuildId)'
jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Docker@1
        displayName: 'Build front image'
        inputs:
          dockerFile: ./lab-survey-front/Dockerfile
          imageName: 'lab-survey-front:$(Build.BuildId)'
          workingDirectory: ./lab-survey-front
      - task: Docker@1
        displayName: 'Build api image'
        inputs:
          dockerFile: ./lab-survey-api/lab-survey-api/Dockerfile
          imageName: $(imageNameApi)
          workingDirectory: ./lab-survey-api/lab-survey-api/
