name: 1.0.$(date:yyyyMMdd)$(rev:.rrr)
variables:
  imageNameFront: lab-survey-front:$(Build.BuildNumber)
  imageNameApi: lab-survey-api:$(Build.BuildNumber)
trigger:
  - master
jobs:
  - job: Docker lab-survey-front
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Docker@1
        displayName: 'Build docker image'
        inputs:
          dockerFile: ./lab-survey-front/Dockerfile
          imageName: $(imageNameFront)
          workingDirectory: ./lab-survey-front
  - job: Docker lab-survey-api
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Docker@1
        displayName: 'Build docker image'
        inputs:
          dockerFile: ./lab-survey-api/lab-survey-api/Dockerfile
          imageName: $(imageNameApi)
          workingDirectory: ./lab-survey-api/lab-survey-api/
