version: '3'

services:
  lab-survey-redis:
    image: redis
    container_name: lab-survey-redis
    ports:
      - '6379:6379'

  lab-survey-api:
    image: lab-survey-api
    container_name: lab-survey-api
    build:
      context: ./lab-survey-api/lab-survey-api/
      dockerfile: Dockerfile
    environment:
      REDIS: lab-survey-redis
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - '8081:5000'

  lab-survey-front:
    image: lab-survey-front
    build:
      context: ./lab-survey-front
      dockerfile: Dockerfile
    container_name: lab-survey-front
    ports:
      - '8080:80'
